import { useState, useEffect } from "react";
import Head from "next/head";
import Image from "next/image";
//components
import { Button, MetaAdvice } from "../components/";
// styles
import styles from "../styles/views/index.module.scss";
//images
import teacher from "../public/img/teacher.gif";
import fresher1 from "../public/img/fresherindex1.png";
import fresher2 from "../public/img/fresherindex2.png";
import fresher3 from "../public/img/fresherindex3.png";
import vsBar from "../public/img/vsBars/vsBar1.png";
import lilFresher1 from "../public/img/lilfresher1.png";
import lilFresher2 from "../public/img/lilfresher2.png";
import lilFresher3 from "../public/img/lilfresher3.png";
import desk from "../public/img/desk.png";
// icons
import { IoDocumentTextOutline, IoDocumentOutline } from "react-icons/io5";

// '/' directory content
export default function Home() {

  // install metamask advice
  const [showAdvice, setShowAdvice] = useState(false);

  //check if metamask is installed 
  useEffect(() => {
    if (typeof window.ethereum == 'undefined') {
      setShowAdvice(true);
    }
  },[])

  return (
    <div className={styles.wrapper}>
      {/* HTML HEAD */}
      <Head>
        <title>Freshers</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* HTML TEMPLATE */}
      <Head>
        <title>Freshers - Jugar</title>
      </Head>
      <section className={styles.main}>
        <div className={styles.text}>
          <h1 className={styles.title}>
            {" "}
            Mintea NFT's, <br /> <span className={styles.test}>
              Haz un Parcial
            </span>{" "}
            <br /> Consigue <span className={styles.ujg}> UJAP GOLD! </span>{" "}
          </h1>
          <p className={styles.slogan}>
            Freshers es un juego Play to Earn hecho con fines de Aprendizaje/Educativo
          </p>
          <div className={styles.buttons}>
            <a href="https://temispita9000.gitbook.io/documentacion-ujapgame/">
              <Button onClick={undefined}>
                <IoDocumentTextOutline /> &nbsp; Documentacion
              </Button>
            </a>
            <a href="https://temispita9000.gitbook.io/cryptos/" target="_blank">
              <Button onClick={undefined}>
                <IoDocumentOutline /> &nbsp; Whitepaper
              </Button>
            </a>
          </div>
        </div>
        <div className={styles.scene}>
          <div
            className={styles.vsBar}
            style={{ backgroundImage: `url(${vsBar.src})` }}
          >
            <div className={styles.fresher}>
              <div>
                <Image src={fresher1} alt="fresher1" height={100} width={200} />
              </div>
              <div>
                <Image src={fresher2} alt="fresher2" height={100} width={200} />
              </div>
              <div>
                <Image src={fresher3} alt="fresher3" height={100} width={200} />
              </div>
            </div>
          </div>
          <section className={styles.freshers}>
            <Image src={lilFresher1} width={80} height={80} />
            <Image src={lilFresher2} width={80} height={80} />
            <Image src={lilFresher3} width={80} height={80} />
          </section>
          <section className={styles.desks}>
            <Image src={desk} width={80} height={80} />
            <Image src={desk} width={80} height={80} />
            <Image src={desk} width={80} height={80} />
          </section>
          <section className={styles.teacher}>
            <Image src={teacher} width={80} height={80} />
          </section>
        </div>
      </section>
      {showAdvice ? <MetaAdvice closeAdvice={setShowAdvice}/> : null}
    </div>
  );
}
