import Head from "next/head";
// styles
import styles from "../styles/Home.module.scss";

// '/' directory content
export default function Home() {
  return (
    <div className={styles.container}>
      {/* HTML HEAD */}
      <Head>
        <title>Game</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* HTML TEMPLATE */}
    </div>
  );
}
